name: Nginx-app$
on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag testing/nginx-app:1.0

    - name: "Configure AWS Credentials" 
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION }} 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Amazon ECR "Login" Action for GitHub Actions
      uses: aws-actions/amazon-ecr-login@v2

    - name: Push the Docker Image to ECR
      run: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 762233743348.dkr.ecr.eu-north-1.amazonaws.com
        docker tag testing/nginx-app:1.0 762233743348.dkr.ecr.eu-north-1.amazonaws.com/testing/nginx-app:1.0
        docker push 762233743348.dkr.ecr.eu-north-1.amazonaws.com/testing/nginx-app:1.0
